#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TF_DIR="$SCRIPT_DIR/../terraform"
REGION=$(cd "$TF_DIR" && terraform output -raw 2>/dev/null | grep -m1 "aws_region" || echo "us-east-1")

echo "=== W5 Evidence Collection Tests ==="
echo "Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo ""

# Get Terraform outputs
cd "$TF_DIR"
APP_IP=$(terraform output -raw app_instance_private_ip 2>/dev/null || echo "UNKNOWN")
TEST_IP=$(terraform output -raw test_instance_private_ip 2>/dev/null || echo "UNKNOWN")
API_URL=$(terraform output -raw api_gateway_url 2>/dev/null || echo "UNKNOWN")
API_KEY=$(terraform output -raw api_key_value 2>/dev/null || echo "UNKNOWN")
DLQ_URL=$(terraform output -raw dlq_url 2>/dev/null || echo "UNKNOWN")
FLOW_LOG_APP=$(terraform output -raw flow_log_group_app 2>/dev/null || echo "UNKNOWN")
FLOW_LOG_DATA=$(terraform output -raw flow_log_group_data 2>/dev/null || echo "UNKNOWN")
FIREWALL_LOG=$(terraform output -raw firewall_alert_log_group 2>/dev/null || echo "UNKNOWN")
LAMBDA_NAME="geekbrain-kb-auto-sync-dev"

echo "=========================================="
echo "MH1: VPC Peering + Flow Logs"
echo "=========================================="
echo ""
echo "[Test 1.1] Connectivity: ping from Test EC2 → App EC2"
echo "  Run on Test EC2 (${TEST_IP}):"
echo "    ping -c 3 ${APP_IP}"
echo ""
echo "[Test 1.2] Connectivity: curl from Test EC2 → App EC2"
echo "  Run on Test EC2:"
echo "    curl -s http://${APP_IP}:8001/docs"
echo ""
echo "[Test 1.3] VPC Flow Logs sample"
echo "  aws logs filter-log-events \\"
echo "    --log-group-name ${FLOW_LOG_APP} \\"
echo "    --limit 5 \\"
echo "    --region ${REGION}"
echo ""

echo "=========================================="
echo "MH2: Network Firewall"
echo "=========================================="
echo ""
echo "[Test 2.1] BLOCKED request (negative test)"
echo "  Run on App EC2:"
echo "    curl -v --max-time 5 https://evil.example.com"
echo "  Expected: Connection timeout/refused"
echo ""
echo "[Test 2.2] ALLOWED request (AWS services)"
echo "  Run on App EC2:"
echo "    curl -s https://bedrock-runtime.${REGION}.amazonaws.com"
echo "  Expected: Connection succeeds (may return 403 auth error, but connection works)"
echo ""
echo "[Test 2.3] Check Firewall Alert Logs"
echo "  aws logs filter-log-events \\"
echo "    --log-group-name ${FIREWALL_LOG} \\"
echo "    --limit 5 \\"
echo "    --region ${REGION}"
echo ""

echo "=========================================="
echo "MH3: EFS + Backup"
echo "=========================================="
echo ""
echo "[Test 3.1] EFS mounted"
echo "  Run on App EC2:"
echo "    df -h | grep nfs"
echo "    ls /mnt/efs/knowledge_base/"
echo ""
echo "[Test 3.2] Write/Read test"
echo "  Run on App EC2:"
echo "    echo 'W5 EFS test $(date)' > /mnt/efs/test_w5.txt"
echo "    cat /mnt/efs/test_w5.txt"
echo ""
echo "[Test 3.3] Backup plan status"
echo "  aws backup list-backup-plans --region ${REGION}"
echo ""
echo "[Test 3.4] Trigger on-demand backup (EFS)"
EFS_ID=$(terraform output -raw efs_filesystem_id 2>/dev/null || echo "UNKNOWN")
VAULT_NAME=$(terraform output -raw backup_vault_name 2>/dev/null || echo "UNKNOWN")
BACKUP_ROLE_ARN="arn:aws:iam::$(aws sts get-caller-identity --query Account --output text):role/geekbrain-backup-role"
echo "  aws backup start-backup-job \\"
echo "    --backup-vault-name ${VAULT_NAME} \\"
echo "    --resource-arn arn:aws:elasticfilesystem:${REGION}:ACCOUNT:file-system/${EFS_ID} \\"
echo "    --iam-role-arn ${BACKUP_ROLE_ARN} \\"
echo "    --region ${REGION}"
echo ""
echo "[Test 3.5] Restore test (after backup completes)"
echo "  1. aws backup list-recovery-points-by-backup-vault --backup-vault-name ${VAULT_NAME}"
echo "  2. aws backup start-restore-job --recovery-point-arn <ARN> --iam-role-arn <ROLE> --metadata '{...}'"
echo "  3. Mount restored EFS and verify: cat /mnt/efs-restored/knowledge_base/team_platform.md"
echo ""

echo "=========================================="
echo "MH4: API Gateway + Auth"
echo "=========================================="
echo ""
echo "[Test 4.1] Authenticated request → 200"
echo "  curl -s -o /dev/null -w '%{http_code}' \\"
echo "    -X POST -H 'x-api-key: ${API_KEY}' \\"
echo "    '${API_URL}'"
echo ""
echo "Running test..."
HTTP_CODE=$(curl -s -o /dev/null -w '%{http_code}' -X POST -H "x-api-key: ${API_KEY}" "${API_URL}" 2>/dev/null || echo "FAILED")
echo "  Result: HTTP ${HTTP_CODE}"
echo ""
echo "[Test 4.2] Unauthenticated request → 403"
echo "  curl -s -o /dev/null -w '%{http_code}' -X POST '${API_URL}'"
echo ""
echo "Running test..."
HTTP_CODE=$(curl -s -o /dev/null -w '%{http_code}' -X POST "${API_URL}" 2>/dev/null || echo "FAILED")
echo "  Result: HTTP ${HTTP_CODE}"
echo ""

echo "=========================================="
echo "MH5: Serverless Scaling"
echo "=========================================="
echo ""
echo "[Test 5.1] Reserved Concurrency"
echo "  aws lambda get-function-concurrency --function-name ${LAMBDA_NAME} --region ${REGION}"
echo ""
echo "Running test..."
aws lambda get-function-concurrency --function-name "${LAMBDA_NAME}" --region "${REGION}" 2>/dev/null || echo "  (run manually)"
echo ""
echo "[Test 5.2] Trigger throttle (upload multiple files)"
echo "  for i in {1..5}; do"
echo "    aws s3 cp /dev/null s3://geekbrain-kb-dev/knowledge_base/test_\${i}.md --region ${REGION} &"
echo "  done"
echo "  wait"
echo "  # Check CloudWatch for Throttles metric"
echo ""
echo "[Test 5.3] DLQ messages"
echo "  aws sqs receive-message --queue-url ${DLQ_URL} --region ${REGION}"
echo ""

echo "=========================================="
echo "Negative Security Tests"
echo "=========================================="
echo ""
echo "[Neg-1] No public IP on app EC2 (MH1)"
echo "  aws ec2 describe-instances --filters 'Name=tag:Name,Values=geekbrain-app-instance' \\"
echo "    --query 'Reservations[].Instances[].PublicIpAddress' --region ${REGION}"
echo ""
echo "[Neg-2] Firewall blocks non-AWS domain (MH2)"
echo "  (See Test 2.1 above)"
echo ""
echo "[Neg-3] EFS SG rejects non-app traffic (MH3)"
echo "  Run from Test EC2: mount -t nfs4 EFS_DNS:/ /tmp/test"
echo "  Expected: Connection timeout (test-sg not in efs-sg ingress)"
echo ""
echo "[Neg-4] API Gateway without key → 403 (MH4)"
echo "  (See Test 4.2 above)"
echo ""
echo "[Neg-5] Lambda throttled beyond concurrency (MH5)"
echo "  (See Test 5.2 above - check for TooManyRequestsException)"
echo ""

echo "=========================================="
echo "Carry-Forward Verification"
echo "=========================================="
echo ""
echo "[CF-1] App end-to-end query"
echo "  Run on Test EC2:"
echo "    curl -s -X POST http://${APP_IP}:8001/query \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"query\": \"Who is the Team Platform lead?\"}'"
echo ""

echo "=== Tests Complete ==="
